### ISSUE TITLE
RBAC roles and Deployment YAMLs

### ISSUE THREAD

**Issue by nmagnezi** [nmagnezi/observatorium-operator#41]

**Comment by rollandf** [comment]
The yamls are here:
https://github.com/nmagnezi/observatorium-operator/tree/master/config/manager
https://github.com/nmagnezi/observatorium-operator/tree/master/config/rbac

- Need to update to the image in quai

- Test to see we have all the need RBAC in k8s and OpenShift

**Comment by rollandf** [comment]
Seems the RBAC is missing permissions.
Need to add annotations and see how to generate with controller-gen tool.

**Comment by nmagnezi** [comment]
The error I get at the moment is:
```
➜  ~ ion.go:330] error retrieving resource lock observatorium/controller-leader-election-helper: configmaps "controller-leader-election-helper" is forbidden: User "system:serviceaccount:observatorium:default" cannot get resource "configmaps" in API group "" in the namespace "observatorium"
```

I'm working o resolve it.
