### ISSUE TITLE
After installation on OCP minio thanos-receive thanos-store pods are on pending status 

### ISSUE THREAD

**Issue by iovadia** [nmagnezi/observatorium-operator#57]
1. Install OCP 4.3
2. Crete 3 PVs
3. apply StorageClass
4. Run the following comands
https://github.com/nmagnezi/observatorium-operator/blob/master/README.md

Results:
=======
pod/minio pod/thanos-store-0 pod/thanos-receive-default-0 are on status pending

**Comment by iovadia** [comment]
oc get events -n minio 
LAST SEEN   TYPE      REASON               OBJECT                        MESSAGE
<unknown>   Warning   FailedScheduling     pod/minio-6d877b9dcd-4qj8p    pod has unbound immediate PersistentVolumeClaims (repeated 5 times)
<unknown>   Warning   FailedScheduling     pod/minio-6d877b9dcd-4qj8p    pod has unbound immediate PersistentVolumeClaims (repeated 5 times)

**Comment by iovadia** [comment]
oc get events -n observatorium
<unknown>   Warning   FailedScheduling     pod/thanos-store-0                                                   pod has unbound immediate PersistentVolumeClaims (repeated 5 times)
<unknown>   Warning   FailedScheduling     pod/thanos-store-0                                                   pod has unbound immediate PersistentVolumeClaims (repeated 5 times)
4m53s       Warning   ProvisioningFailed   persistentvolumeclaim/thanos-store-data-thanos-store-0               no volume plugin matched

**Comment by agurenko** [comment]
So, PVs should have

1. storageClassName: standard
2. accessModes set to ReadWriteOnce

Those 2 are requirements, otherwise scheduler fails to create a claim.

**Comment by rollandf** [comment]
Nice, all those are storage related, nothing about the operator.

Could you add to README file the steps you do for setting up the storage?

**Comment by ybettan** [comment]
Any documentation on how to solve this issue?

**Comment by rollandf** [comment]
Closing. Not related to operator.
